<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent><groupId>com.ferry</groupId><artifactId>ferry-mall-server</artifactId><version>1.0.0-SNAPSHOT</version></parent>
    <artifactId>ferry-module-logistics</artifactId>
    <packaging>pom</packaging>
    <name>ferry-module-logistics</name>
    <description>物流中心模块</description>
    <modules>
        <module>ferry-module-logistics-api</module>
        <module>ferry-module-logistics-server</module>
    </modules>
</project>
