export default defineAppConfig({
  pages: [
    'pages/index/index',
    'pages/category/index',
    'pages/cart/index',
    'pages/user/index',
    'pages/product/detail',
    'pages/product/comment',
    'pages/product/comment-post',
    'pages/order/confirm',
    'pages/order/list',
    'pages/order/detail',
    'pages/payment/pay',
    'pages/payment/result',
    'pages/address/list',
    'pages/address/edit',
    'pages/coupon/list',
    'pages/coupon/my',
    'pages/integral/list',
    'pages/level/index',
    'pages/favorite/list',
    'pages/footprint/list',
    'pages/seckill/index',
    'pages/seckill/detail',
    'pages/groupon/index',
    'pages/groupon/detail',
    'pages/bargain/index',
    'pages/bargain/detail',
    'pages/commission/index',
    'pages/commission/withdraw',
    'pages/commission/records',
    'pages/commission/team',
    'pages/points/mall',
    'pages/message/list',
    'pages/live/list',
    'pages/bind/phone',
    'pages/search/index',
    'pages/merchant/apply',
    'pages/store/detail',
    'pages/aftermarket/apply',
    'pages/logistics/trace',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#ffffff',
    navigationBarTitleText: 'Ferry Mall',
    navigationBarTextStyle: 'black'
  },
  tabBar: {
    color: '#64748b',
    selectedColor: '#2563eb',
    backgroundColor: '#ffffff',
    list: [
      { pagePath: 'pages/index/index', text: '首页' },
      { pagePath: 'pages/category/index', text: '分类' },
      { pagePath: 'pages/cart/index', text: '购物车' },
      { pagePath: 'pages/user/index', text: '我的' }
    ]
  }
})
