-- 租户表
CREATE TABLE IF NOT EXISTS sys_tenant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    contact_name VARCHAR(64),
    contact_mobile VARCHAR(32),
    package_id BIGINT DEFAULT 0,
    expire_time TIMESTAMP,
    account_count INT NOT NULL DEFAULT 0,
    status TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 系统用户表
CREATE TABLE IF NOT EXISTS sys_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    username VARCHAR(64) NOT NULL,
    password VARCHAR(128) NOT NULL,
    nickname VARCHAR(64) NOT NULL,
    dept_id BIGINT DEFAULT 0,
    status TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_sys_user_tenant ON sys_user(tenant_id);

-- 角色表
CREATE TABLE IF NOT EXISTS sys_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    name VARCHAR(64) NOT NULL,
    code VARCHAR(64) NOT NULL,
    data_scope TINYINT NOT NULL DEFAULT 1,
    status TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 菜单表
CREATE TABLE IF NOT EXISTS sys_menu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    permission VARCHAR(128),
    type TINYINT NOT NULL DEFAULT 1,
    parent_id BIGINT NOT NULL DEFAULT 0,
    sort INT NOT NULL DEFAULT 0,
    path VARCHAR(255),
    component VARCHAR(255),
    icon VARCHAR(64),
    status TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 用户角色关联
CREATE TABLE IF NOT EXISTS sys_user_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL
);

-- 角色菜单关联
CREATE TABLE IF NOT EXISTS sys_role_menu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL,
    menu_id BIGINT NOT NULL
);

-- 部门表
CREATE TABLE IF NOT EXISTS sys_dept (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    parent_id BIGINT NOT NULL DEFAULT 0,
    name VARCHAR(64) NOT NULL,
    sort INT NOT NULL DEFAULT 0,
    leader VARCHAR(64),
    status TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 字典表
CREATE TABLE IF NOT EXISTS sys_dict (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(64) NOT NULL,
    name VARCHAR(64) NOT NULL,
    status TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 字典项表
CREATE TABLE IF NOT EXISTS sys_dict_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dict_id BIGINT NOT NULL,
    label VARCHAR(64) NOT NULL,
    value VARCHAR(64) NOT NULL,
    sort INT NOT NULL DEFAULT 0,
    status TINYINT NOT NULL DEFAULT 1
);

-- 登录日志表
CREATE TABLE IF NOT EXISTS sys_login_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    user_id BIGINT,
    user_type TINYINT NOT NULL DEFAULT 1,
    username VARCHAR(64),
    ip VARCHAR(64),
    user_agent VARCHAR(512),
    result TINYINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 操作日志表
CREATE TABLE IF NOT EXISTS sys_operate_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    user_id BIGINT,
    module VARCHAR(64),
    name VARCHAR(64),
    type TINYINT NOT NULL DEFAULT 0,
    request_method VARCHAR(16),
    request_url VARCHAR(512),
    request_params VARCHAR(2048),
    response_body VARCHAR(2048),
    user_ip VARCHAR(64),
    duration INT,
    result TINYINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 商品分类表
CREATE TABLE IF NOT EXISTS product_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    parent_id BIGINT NOT NULL DEFAULT 0,
    name VARCHAR(64) NOT NULL,
    sort INT NOT NULL DEFAULT 0,
    visible TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_product_category_tenant ON product_category(tenant_id);

-- 商品SPU表
CREATE TABLE IF NOT EXISTS product_spu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    category_id BIGINT NOT NULL,
    store_id BIGINT DEFAULT 1,
    name VARCHAR(128) NOT NULL,
    subtitle VARCHAR(255),
    cover_url VARCHAR(512),
    price_cent INT NOT NULL,
    market_price_cent INT NOT NULL DEFAULT 0,
    stock INT NOT NULL DEFAULT 0,
    sales INT NOT NULL DEFAULT 0,
    status TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_product_spu_tenant ON product_spu(tenant_id);

-- 会员用户表
CREATE TABLE IF NOT EXISTS member_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    openid VARCHAR(64) NOT NULL,
    unionid VARCHAR(64),
    mobile VARCHAR(32),
    nickname VARCHAR(64) NOT NULL,
    avatar_url VARCHAR(512),
    points INT NOT NULL DEFAULT 0,
    status TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_member_user_openid ON member_user(openid);
CREATE INDEX IF NOT EXISTS idx_member_user_tenant ON member_user(tenant_id);

-- 会员等级表
CREATE TABLE IF NOT EXISTS member_level (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    name VARCHAR(64) NOT NULL,
    min_points INT NOT NULL DEFAULT 0,
    discount_percent INT NOT NULL DEFAULT 100,
    status TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 订单主表
CREATE TABLE IF NOT EXISTS order_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    order_no VARCHAR(64) NOT NULL UNIQUE,
    member_id BIGINT NOT NULL,
    total_amount_cent INT NOT NULL DEFAULT 0,
    discount_amount_cent INT NOT NULL DEFAULT 0,
    pay_amount_cent INT NOT NULL,
    status TINYINT NOT NULL,
    receiver_name VARCHAR(64) NOT NULL,
    receiver_mobile VARCHAR(32) NOT NULL,
    receiver_address VARCHAR(255) NOT NULL,
    remark VARCHAR(500),
    pay_time TIMESTAMP,
    delivery_time TIMESTAMP,
    receive_time TIMESTAMP,
    cancel_time TIMESTAMP,
    cancel_reason VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_order_info_tenant ON order_info(tenant_id);

-- 订单商品项表
CREATE TABLE IF NOT EXISTS order_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    order_id BIGINT NOT NULL,
    spu_id BIGINT NOT NULL,
    sku_id BIGINT,
    store_id BIGINT NOT NULL DEFAULT 0,
    product_name VARCHAR(128) NOT NULL,
    product_image VARCHAR(512),
    price_cent INT NOT NULL,
    quantity INT NOT NULL,
    total_cent INT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_order_item_tenant ON order_item(tenant_id);

-- 商家信息表
CREATE TABLE IF NOT EXISTS merchant_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    name VARCHAR(128) NOT NULL,
    contact_name VARCHAR(64) NOT NULL,
    contact_mobile VARCHAR(32) NOT NULL,
    license_no VARCHAR(64),
    status TINYINT NOT NULL DEFAULT 10,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_merchant_info_tenant ON merchant_info(tenant_id);

-- 店铺信息表
CREATE TABLE IF NOT EXISTS store_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    merchant_id BIGINT NOT NULL,
    name VARCHAR(128) NOT NULL,
    logo_url VARCHAR(512),
    description VARCHAR(255),
    status TINYINT NOT NULL DEFAULT 1,
    score DECIMAL(3,1) NOT NULL DEFAULT 5.0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_store_info_tenant ON store_info(tenant_id);

-- 结算账单表
CREATE TABLE IF NOT EXISTS settlement_bill (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    merchant_id BIGINT NOT NULL,
    merchant_name VARCHAR(128),
    order_amount_cent INT NOT NULL DEFAULT 0,
    commission_cent INT NOT NULL DEFAULT 0,
    payable_cent INT NOT NULL DEFAULT 0,
    status TINYINT NOT NULL DEFAULT 10,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_settlement_bill_tenant ON settlement_bill(tenant_id);

-- 物流轨迹表
CREATE TABLE IF NOT EXISTS logistics_trace (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    order_id BIGINT NOT NULL,
    logistics_no VARCHAR(64) NOT NULL,
    company VARCHAR(64) NOT NULL,
    trace_content VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_logistics_trace_tenant ON logistics_trace(tenant_id);

-- 售后记录表
CREATE TABLE IF NOT EXISTS aftermarket_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    order_id BIGINT NOT NULL,
    reason VARCHAR(255) NOT NULL,
    status TINYINT NOT NULL DEFAULT 10,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_aftermarket_record_tenant ON aftermarket_record(tenant_id);

-- 优惠券表
CREATE TABLE IF NOT EXISTS marketing_coupon (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    name VARCHAR(128) NOT NULL,
    discount_cent INT NOT NULL,
    threshold_cent INT NOT NULL,
    total_count INT NOT NULL,
    received_count INT NOT NULL DEFAULT 0,
    status TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_marketing_coupon_tenant ON marketing_coupon(tenant_id);

-- 营销活动表
CREATE TABLE IF NOT EXISTS marketing_promotion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    name VARCHAR(128) NOT NULL,
    promotion_type VARCHAR(32) NOT NULL,
    rule_json VARCHAR(1024),
    status TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_marketing_promotion_tenant ON marketing_promotion(tenant_id);

-- 支付渠道表
CREATE TABLE IF NOT EXISTS payment_channel (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    channel_code VARCHAR(32) NOT NULL,
    channel_name VARCHAR(64) NOT NULL,
    enabled TINYINT NOT NULL DEFAULT 1,
    config_json VARCHAR(2048)
);
CREATE INDEX IF NOT EXISTS idx_payment_channel_tenant ON payment_channel(tenant_id);

-- 支付记录表
CREATE TABLE IF NOT EXISTS payment_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    payment_no VARCHAR(64) NOT NULL UNIQUE,
    order_no VARCHAR(64) NOT NULL,
    channel VARCHAR(32) NOT NULL,
    amount_cent INT NOT NULL,
    status TINYINT NOT NULL DEFAULT 10,
    third_party_no VARCHAR(128),
    callback_payload CLOB,
    paid_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_payment_record_tenant ON payment_record(tenant_id);

-- 退款记录表
CREATE TABLE IF NOT EXISTS payment_refund (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    refund_no VARCHAR(64) NOT NULL UNIQUE,
    payment_no VARCHAR(64) NOT NULL,
    order_no VARCHAR(64) NOT NULL,
    refund_amount_cent INT NOT NULL DEFAULT 0,
    status TINYINT NOT NULL DEFAULT 10,
    reason VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_payment_refund_tenant ON payment_refund(tenant_id);

-- 会员优惠券关联表
CREATE TABLE IF NOT EXISTS member_coupon (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    member_id BIGINT NOT NULL,
    coupon_id BIGINT NOT NULL,
    coupon_name VARCHAR(128) NOT NULL,
    discount_cent INT NOT NULL,
    threshold_cent INT NOT NULL,
    status TINYINT NOT NULL DEFAULT 1,
    used_time TIMESTAMP,
    expire_time TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_member_coupon_member ON member_coupon(member_id);

-- 会员积分记录表
CREATE TABLE IF NOT EXISTS member_integral_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    member_id BIGINT NOT NULL,
    change_count INT NOT NULL DEFAULT 0,
    current_points INT NOT NULL DEFAULT 0,
    reason VARCHAR(255),
    type TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_member_integral_member ON member_integral_record(member_id);

-- 轮播图表
CREATE TABLE IF NOT EXISTS product_banner (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    title VARCHAR(128) NOT NULL,
    image_url VARCHAR(512) NOT NULL,
    link_url VARCHAR(512),
    sort INT NOT NULL DEFAULT 0,
    status TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_product_banner_tenant ON product_banner(tenant_id);

-- 商品评价表
CREATE TABLE IF NOT EXISTS product_comment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    spu_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    member_nickname VARCHAR(64),
    member_avatar VARCHAR(512),
    content VARCHAR(1024) NOT NULL,
    rating INT NOT NULL DEFAULT 5,
    images VARCHAR(2048),
    status TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_product_comment_spu ON product_comment(spu_id);

-- 收藏表
CREATE TABLE IF NOT EXISTS member_favorite (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    member_id BIGINT NOT NULL,
    spu_id BIGINT NOT NULL,
    spu_name VARCHAR(128),
    spu_cover VARCHAR(512),
    price_cent INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_member_favorite_member ON member_favorite(member_id);

-- 足迹表
CREATE TABLE IF NOT EXISTS member_footprint (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    member_id BIGINT NOT NULL,
    spu_id BIGINT NOT NULL,
    spu_name VARCHAR(128),
    spu_cover VARCHAR(512),
    price_cent INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_member_footprint_member ON member_footprint(member_id);

-- 秒杀活动表
CREATE TABLE IF NOT EXISTS seckill_activity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    name VARCHAR(128) NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    status TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 秒杀商品关联表
CREATE TABLE IF NOT EXISTS seckill_product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    activity_id BIGINT NOT NULL,
    spu_id BIGINT NOT NULL,
    seckill_price_cent INT NOT NULL,
    stock INT NOT NULL DEFAULT 0,
    sold INT NOT NULL DEFAULT 0,
    status TINYINT NOT NULL DEFAULT 1
);

-- 拼团活动表
CREATE TABLE IF NOT EXISTS groupon_activity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    name VARCHAR(128) NOT NULL,
    spu_id BIGINT NOT NULL,
    groupon_price_cent INT NOT NULL,
    require_count INT NOT NULL DEFAULT 2,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    status TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 拼团记录表
CREATE TABLE IF NOT EXISTS groupon_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    activity_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    status TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 砍价活动表
CREATE TABLE IF NOT EXISTS bargain_activity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    name VARCHAR(128) NOT NULL,
    spu_id BIGINT NOT NULL,
    original_price_cent INT NOT NULL,
    floor_price_cent INT NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    status TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 砍价记录表
CREATE TABLE IF NOT EXISTS bargain_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    activity_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    current_price_cent INT NOT NULL,
    status TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 推广员表
CREATE TABLE IF NOT EXISTS commission_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    member_id BIGINT NOT NULL,
    parent_id BIGINT DEFAULT 0,
    total_commission_cent INT NOT NULL DEFAULT 0,
    available_commission_cent INT NOT NULL DEFAULT 0,
    status TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 佣金记录表
CREATE TABLE IF NOT EXISTS commission_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    member_id BIGINT NOT NULL,
    order_no VARCHAR(64),
    commission_cent INT NOT NULL DEFAULT 0,
    type TINYINT NOT NULL DEFAULT 1,
    status TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 积分商品表
CREATE TABLE IF NOT EXISTS points_product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    name VARCHAR(128) NOT NULL,
    cover_url VARCHAR(512),
    points INT NOT NULL,
    stock INT NOT NULL DEFAULT 0,
    sort INT NOT NULL DEFAULT 0,
    status TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 积分兑换记录表
CREATE TABLE IF NOT EXISTS points_exchange (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    member_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    product_name VARCHAR(128),
    points INT NOT NULL,
    status TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 消息通知表
CREATE TABLE IF NOT EXISTS message_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    member_id BIGINT NOT NULL,
    title VARCHAR(128) NOT NULL,
    content VARCHAR(1024),
    type TINYINT NOT NULL DEFAULT 1,
    is_read TINYINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_message_member ON message_record(member_id);

-- 直播间表
CREATE TABLE IF NOT EXISTS live_room (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    name VARCHAR(128) NOT NULL,
    cover_url VARCHAR(512),
    anchor_name VARCHAR(64),
    stream_url VARCHAR(512),
    status TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 购物车表
CREATE TABLE IF NOT EXISTS member_cart (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    member_id BIGINT NOT NULL,
    spu_id BIGINT NOT NULL,
    sku_id BIGINT,
    quantity INT NOT NULL DEFAULT 1,
    selected TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_member_cart_member ON member_cart(member_id);
